---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 2/9/2022 3:31 下午
---


local UIMessageNames = {
    ---@public UI_UPDATE_PLAYER_HURT 收到伤害
    UI_UPDATE_PLAYER_HURT = "UIUpdatePlayerHurt",
}

return ConstClass("UIMessageNames", UIMessageNames)