---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 10/8/2022 2:22 下午
---

local GuessTheIdiomStartScene = BaseClass("GuessTheIdiomStartScene", BaseScene)
local base = BaseScene

function GuessTheIdiomStartScene:OnCreate()
    base.OnCreate(self)
    self:AddPreloadResource(UIConfig[UIWindowNames.UIGuessTheIdiomStart].PrefabPath, typeof(CS.UnityEngine.GameObject), 1)
    self:AddPreloadResource(UIConfig[UIWindowNames.UIGuessTheIdiomLevel].PrefabPath, typeof(CS.UnityEngine.GameObject), 1)
end

-- 准备工作
function GuessTheIdiomStartScene:OnComplete(self)
    base.OnComplete(self)
    UIManager:GetInstance():OpenWindow(UIWindowNames.UIGuessTheIdiomStart)
end

return GuessTheIdiomStartScene