---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 16/8/2022 7:15 下午
---

local Idiom_UIMessageNames = {
    ON_INPUT_TEXT = "OnInputText",---完输点击文字输入
    ON_REMOVE_TEXT = "OnRemoveText",---完输点击文字输入
    
}

return ConstClass("Idiom_UIMessageNames", Idiom_UIMessageNames)