---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 18/8/2022 1:58 下午
---

---@class Idiom_DataMessageNames 猜成语的数据通知
local Idiom_DataMessageNames = {}

---@public ON_GAME_START 开始游戏通知
Idiom_DataMessageNames.ON_GAME_START = "Idiom_Game_Start"

return ConstClass("Idiom_DataMessageNames", Idiom_DataMessageNames)