---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 23/8/2022 5:24 下午
---
local IdiomUIBtnOnClick = BaseClass("IdiomUIBtnOnClick", UIBaseComponent)
local base = UIBaseComponent

function IdiomUIBtnOnClick:OnCreate()
    base.OnCreate(self)
    self.button = self.transform:GetComponent("Button")

    self._callback = Bind(self, self._OnClicked)
    self.button.onClick:AddListener(self._callback)
end

function IdiomUIBtnOnClick:_OnClicked()
    CS.DarkTonic.MasterAudio.MasterAudio.PlaySound("on_clicked")
end

function IdiomUIBtnOnClick:OnDisable()
    base.OnDisable(self)
    self.button.onClick:RemoveListener(self._callback)
end

return IdiomUIBtnOnClick