---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 16/8/2022 7:15 下午
---

local Idiom_UIMessageNames = {
    
}

return ConstClass("Idiom_UIMessageNames", Idiom_UIMessageNames)