---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 23/8/2022 5:14 下午
---

local Idiom_UI_SoundToggle = BaseClass("Idiom_UI_SoundToggle", UIBaseComponent)
local base = UIBaseComponent

function Idiom_UI_SoundToggle:OnCreate()
    base.OnCreate(self)
    self.sound_toggle = self.transform:GetComponent("Toggle")
    self._onValueChanged = Bind(self, self._OnValueChanged)
    
    self.sound_toggle.onValueChanged:AddListener(self._onValueChanged)
end

function Idiom_UI_SoundToggle:OnEnable()
    self.sound_toggle.isOn = not CS.DarkTonic.MasterAudio.MasterAudio.MixerMuted
end

function Idiom_UI_SoundToggle:OnDestroy()
    base.OnDestroy(self);
    self.sound_toggle.onValueChanged:RemoveListener(self._onValueChanged)
end

function Idiom_UI_SoundToggle:_OnValueChanged(isOn)
    CS.DarkTonic.MasterAudio.MasterAudio.MixerMuted = not isOn

end

return Idiom_UI_SoundToggle