---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 16/8/2022 4:23 下午
---

local UIGamingInputPanel = BaseClass("UIGamingInputPanel", UIBaseComponent)
local base = UIBaseComponent

---界面中文字按钮的个数
local buttonCount = 16

function UIGamingInputPanel:OnCreate(model, inputCallback, removeCallback)
    assert(model, "model是空")
    base.OnCreate(self)
    self.model = model
    self.stateImagPosTs = self.transform.parent:Find("input_panel/btn_pos")

    self.btn_remove = self.transform:Find("btn_remove"):GetComponent("Button")
    self.btn_remove.transform.position = self.stateImagPosTs.position
    self.btn_remove.onClick:AddListener(function()
        if removeCallback then
            removeCallback()
        end
    end)
    self.content = self.transform:Find("content")
    --local btn_text_prefab = ResourcesManager:GetInstance():CoLoadAsync("MinniGames/GuessTheIdiom/GamingPrefab/btn_text.prefab", typeof(GameObject), nil)
    self.textBtnList = {}
    --for index = 1, buttonCount do
    --    local btn_text = GameObject.Instantiate(btn_text_prefab, self.content)
    --    local text = btn_text.transform:Find("text"):GetComponent("Text")
    --
    --    btn_text:GetComponent("Button").onClick:AddListener(function()
    --        if inputCallback then
    --            inputCallback(text.text)
    --        end
    --    end)
    --    table.insert(self.textBtnList, text)
    --end
    --self.gameObject:SetActive(false)
end

function UIGamingInputPanel:OnEnable()
    base.OnEnable(self)
    local btn_text_prefab = ResourcesManager:GetInstance():CoLoadAsync("MinniGames/GuessTheIdiom/GamingPrefab/btn_text.prefab", typeof(GameObject), nil)
    --self.textBtnList = {}
    for index = 1, buttonCount do
        local btn_text = GameObject.Instantiate(btn_text_prefab, self.content)
        local text = btn_text.transform:Find("text"):GetComponent("Text")

        btn_text:GetComponent("Button").onClick:AddListener(function()
            if inputCallback then
                inputCallback(text.text)
            end
        end)
        table.insert(self.textBtnList, text)
    end
    self.gameObject:SetActive(false)
end

---@public InitData 每局游戏初始化游戏数据
function UIGamingInputPanel:InitData()
    local texts = self.model.texts
    for index, btn_text in ipairs(self.textBtnList) do
        btn_text.text = texts[index] or ""
    end
    self.gameObject:SetActive(true)
    self.btn_remove.gameObject:SetActive(true)
end

function UIGamingInputPanel:GameOver(isWin)
    if isWin then
        self.btn_remove.gameObject:SetActive(false)
    else
        self.gameObject:SetActive(false)
    end
end

return UIGamingInputPanel