---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 16/8/2022 3:49 下午
---

local UIGamingOverPanel = BaseClass("UIGamingOverPanel", UIBaseComponent)
local base = UIBaseComponent
local IdiomConfig = require('UI.Config.IdiomConfig')

function UIGamingOverPanel:OnCreate(nextCallback)
    base.OnCreate(self)
    self.btn_next = self.transform:Find("btn_next_idiom"):GetComponent("Button")
    if nextCallback then
        self.btn_next.onClick:AddListener(nextCallback)
    end
    self.wrong_panel_go = self.transform:Find("wrong_panel").gameObject
    self.correct_panel_go = self.transform:Find("correct_panel").gameObject

    self.stateImagPosTs = self.transform.parent:Find("input_panel/btn_pos")

    self.wrong_panel_go.transform:Find("state_img").position = self.stateImagPosTs.position
    self.correct_panel_go.transform:Find("state_img").position = self.stateImagPosTs.position

    self.wrong_text = self.transform:Find("wrong_panel/bg/text"):GetComponent("Text")

    self:SetActive(false)
end

function UIGamingOverPanel:SetNextCallback(nextCallback)
    if nextCallback then
        self.btn_next.onClick:AddListener(nextCallback)
    end
end

---@public ShowWrongPanel 显示打错了
---@param leave number 当前等级
function UIGamingOverPanel:ShowWrongPanel(leave)
    assert(leave, "leave 是空")
    local idiom = IdiomConfig[leave]
    self.wrong_text.text = idiom
    self.wrong_panel_go:SetActive(true)
    self.correct_panel_go:SetActive(false)
    self:SetActive(true)
end

---@public ShowCorrectPanel 赢了
function UIGamingOverPanel:ShowCorrectPanel()
    self.wrong_panel_go:SetActive(false)
    self.correct_panel_go:SetActive(true)
    self:SetActive(true)
end

return UIGamingOverPanel