---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 16/8/2022 3:15 下午
---

---@class SpriteAtlasManager 新版的图集

local SpriteAtlasManager = BaseClass("SpriteAtlasManager", Singleton)
local atlas_typeof = typeof(CS.UnityEngine.U2D.SpriteAtlas)
local endswith = ".spriteatlas"
-- 从图集异步加载图片：回调方式
function SpriteAtlasManager:LoadImageAsync(atlas_path, image_name, callback, ...)
    ResourcesManager:GetInstance():LoadAsync(string.endswith(atlas_path, endswith) and atlas_path or atlas_path .. endswith, atlas_typeof, function(atlas, ...)
        local sprite = atlas:GetSprite(image_name)
        if callback then
            return callback(not IsNull(sprite) and sprite or nil, ...)
        end
    end, ...)
end

-- 从图集异步加载图片：协程方式
function SpriteAtlasManager:CoLoadImageAsync(atlas_path, image_name, progress_callback)
    local atlas = ResourcesManager:GetInstance():CoLoadAsync(string.endswith(atlas_path, endswith) and atlas_path or atlas_path .. endswith, atlas_typeof, progress_callback)
    local sprite = atlas:GetSprite(image_name)
    return not IsNull(sprite) and sprite or nil
end

return SpriteAtlasManager