---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 16/8/2022 3:08 下午
---

local UIImage_Atlas = BaseClass("UIImage_Atlas", UIBaseComponent)
local base = UIBaseComponent

-- 创建
function UIImage_Atlas:OnCreate(atlas_config, original_sprite_name)
    base.OnCreate(self)
    -- Unity侧原生组件
    self.unity_uiimage = UIUtil.FindImage(self.transform)
    self.atlas_config = atlas_config
    
    self.sprite_name = original_sprite_name

    if IsNull(self.unity_uiimage) and not IsNull(self.gameObject) then
        self.gameObject = self.unity_uiimage.gameObject
        self.transform = self.unity_uiimage.transform
    end
end

---@public UIImage_Atlas.SetSpriteName 设置image显示的图片
---@param sprite_name string 图片的名字
function UIImage_Atlas:SetSpriteName(sprite_name)
    assert(self.atlas_config)
    self.sprite_name = sprite_name
end

---@public UIImage_Atlas.SetSpriteNameAndShow 设置image显示的图片并且显示
---@param sprite_name string 图片的名字
function UIImage_Atlas:SetSpriteNameAndShow(sprite_name)
    self:SetSpriteName(sprite_name)
    self:ShowSpriteImg()
end

---@public UIImage_Atlas.ShowSpriteImg 显示图片
function UIImage_Atlas:ShowSpriteImg()
    assert(self.atlas_config, "没有找到图集")
    assert(self.sprite_name, "没有找到图片")
    --local sprite = SpriteAtlasManager:GetInstance():CoLoadImageAsync(self.atlas_config, self.sprite_name)
    SpriteAtlasManager:GetInstance():LoadImageAsync(self.atlas_config, self.sprite_name, function(sprite)
        assert(sprite, "没有获取到图片资源")
        self.unity_uiimage.sprite = sprite
    end)
    --assert(sprite, "没有获取到图片资源")
    --self.unity_uiimage.sprite = sprite
end

---@public UIImage_Atlas.SetAtlas 设置图集
---@param atlas_config string 图集
---@param sprite_name string 图片名字
function UIImage_Atlas:SetAtlas(atlas_config, sprite_name)
    self.atlas_config = atlas_config or self.atlas_config
    self.sprite_name = sprite_name or self.sprite_name
end

return UIImage_Atlas