---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 2/9/2022 11:57 上午
---

---@class UIBloodView 血量显示UI
local UIBloodView = BaseClass("UIBloodView", UIBaseComponent)
local base = UIBaseComponent

function UIBloodView:OnCreate()
    base.OnCreate(self)
    self.sizeDelta = self.rectTransform.sizeDelta
    --self.sprite.type = CS.UnityEngine.UI.Image.Type.Sliced
    --self.sprite.fillCenter = true
end

---@public SetBloodValue 设置当前血量显示100%
---@param value number 血量百分比
function UIBloodView:SetBloodValue(value)
    local size = Vector2.New(self.sizeDelta.x * value, self.sizeDelta.y)
    self.rectTransform.sizeDelta = size
end

return UIBloodView