---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 2/9/2022 4:06 下午
---

local UIPlayerController = BaseClass("UIPlayerController", UIBaseComponent)

function UIPlayerController:OnCreate(leftCallback,rightCallback)
    
end

return UIPlayerController