---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 11/8/2022 8:05 下午
---

local ItemBtnLeave = BaseClass("ItemBtnLeave", UIBaseContainer)
local base = UIBaseContainer
function ItemBtnLeave:OnCreate()
    base.OnCreate(self)
    self.leave = -1
    self.text = self:AddComponent(UITextMeshProUGUI, "text")
    self.lock = self:AddComponent(UIImage, "lock")
    self:IsLock()
end

function ItemBtnLeave:SetLeave(value)
    self.leave = value
    self.text:SetText(self.leave)
end

function ItemBtnLeave:IsLock()
    if self.leave == -1 or false then
        self.lock:SetActive(true)
        self.text:SetActive(false)
    else
        self.lock:SetActive(false)
        self.text:SetActive(true)
    end
end

return ItemBtnLeave