---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 1/9/2022 7:30 下午
---


local UIWindowNames = {
    UIStartLayout = "UIStartLayout",
    UIGamingLayout = "UIGamingLayout",
}

return ConstClass("KingKongWarUIWindowNames", UIWindowNames)