---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 2/9/2022 3:15 下午
---

--[[
-- 数据消息定义，手动添加
--]]

local DataMessageNames = {
    ---@public ON_GAMING_HURT 收到伤害
    ON_GAMING_HURT = "OnGamingHurt"
}

return ConstClass("DataMessageNames", DataMessageNames)