---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 2/9/2022 11:31 上午
---

---@class PlayerData 玩家数据类
local PlayerData = DataClass("PlayerData")
---@public maxBloodVolume 最大血量
PlayerData.maxBloodVolume = 4
---@public nowBloodVolume 当前血量
PlayerData.nowBloodVolume = 4
---@public isRun 是否行动
PlayerData.isRun = false
---@public timeLeft 当前行动剩余时间
PlayerData.timeLeft = 30
---@public isBot 是否是机器人
PlayerData.isBot = false

PlayerData.playerId = 0

function PlayerData:__init(playerId)
    self.playerId = playerId
end

---@public GameStartInitData 每句游戏开始—初始化数据
function PlayerData:GameStartInitData()
    self.nowBloodVolume = PlayerData.maxBloodVolume
end

---@public Hurt 收到伤害
function PlayerData:Hurt()
    self.nowBloodVolume = nowBloodVolume - 1
    DataManager:GetInstance():Broadcast(DataMessageNames.ON_GAMING_HURT, self)
end

return PlayerData